CREATE DATABASE Test_FE_SU22
--ĐỀ FALL 2021 CA 2

--Câu 25
CREATE TABLE FALL(
A INT)

INSERT FALL VALUES (NULL)
INSERT FALL VALUES (NULL)
INSERT FALL VALUES (10)
INSERT FALL VALUES (10)
INSERT FALL VALUES (20)
INSERT FALL VALUES (30)

SELECT AVG(DISTINCT A) FROM FALL

--Câu 20
SELECT 'Nancy' + NULL + 'Smith'
SELECT 1 + NULL + 2


--ĐỀ SUMMER 2022
--Câu 2
CREATE TABLE R(
A INT PRIMARY KEY,
B INT)

CREATE TABLE S(
C INT PRIMARY KEY,
D INT)

DROP TABLE R
DROP TABLE S

INSERT INTO R VALUES (1, 4)
INSERT INTO R VALUES (2, 5)
INSERT INTO R VALUES (3, 6)
INSERT INTO R VALUES (4, 7)

INSERT INTO S VALUES (0, 1)
INSERT INTO S VALUES (1, 0)
INSERT INTO S VALUES (2, 1)

DELETE FROM R
DELETE FROM S

SELECT * FROM R
SELECT * FROM S

SELECT A, B, C, D 
FROM R LEFT OUTER JOIN S
ON R.A = S.C

--Câu 32
CREATE TABLE Arc(
X INT,
Y INT
)

DROP TABLE Arc

INSERT INTO Arc VALUES(1, 2)
INSERT INTO Arc VALUES(1, 2)
INSERT INTO Arc VALUES(2, 3)
INSERT INTO Arc VALUES(3, 4)
INSERT INTO Arc VALUES(3, 4)
INSERT INTO Arc VALUES(4, 1)
INSERT INTO Arc VALUES(4, 1)
INSERT INTO Arc VALUES(4, 2)
INSERT INTO Arc VALUES(4, 2)

DELETE FROM Arc

SELECT * FROM Arc

SELECT X, COUNT(Y)
FROM Arc
GROUP BY X

--Câu 43

CREATE TABLE R2(
A INT,
B INT,
C INT
)

INSERT INTO R2 VALUES (1, 2, 3)
INSERT INTO R2 VALUES (4, 5, 6)
INSERT INTO R2 VALUES (7, 8, 9)

SELECT SUM(B) FROM R2
WHERE C>10

--Câu 49
DELETE FROM Arc
INSERT INTO Arc VALUES(1, 2)
INSERT INTO Arc VALUES(1, 2)
INSERT INTO Arc VALUES(2, 3)
INSERT INTO Arc VALUES(3, 4)
INSERT INTO Arc VALUES(3, 4)
INSERT INTO Arc VALUES(4, 1)
INSERT INTO Arc VALUES(4, 1)
INSERT INTO Arc VALUES(4, 1)
INSERT INTO Arc VALUES(4, 2)

SELECT a1.X, a2.Y, COUNT(*)
FROM Arc a1, Arc a2
WHERE a1.Y = a2.X
GROUP BY a1.X, a2.Y



CREATE TABLE Temp(
Col1 NVARCHAR(10)
)

INSERT INTO Temp (Col1)
VALUES (@TempVal)
PRINT @TempVal
IF @@error!=0
RETURN 1
ELSE RETURN 0

CREATE TABLE team(
Team VARCHAR(20),
Opponent VARCHAR(20)
)

DROP TABLE team

INSERT INTO team VALUES ('Marines', 'Tigers')
INSERT INTO team VALUES ('Ham Fighters', 'Swallows')

SELECT Team, Opponent 
FROM team
WHERE Team LIKE '% %' OR Opponent LIKE '_i%' 

--------------------------------------------
CREATE TABLE R3(
A INT,
B INT
)

CREATE TABLE S3(
B INT,
C INT,
D INT
)

INSERT INTO R3 VALUES(1, 2)
INSERT INTO R3 VALUES(3, 4)
INSERT INTO R3 VALUES(5, 6)

INSERT INTO S3 VALUES(2, 4, 6)
INSERT INTO S3 VALUES(4, 6, 8)
INSERT INTO S3 VALUES(4, 7, 9)

SELECT * FROM R3
SELECT * FROM S3

SELECT *
FROM R3 FULL OUTER JOIN S3
ON R3.B = S3.C
WHERE R3.A>S3.B AND R3.B = S3.C

CREATE TABLE Re(
A INT
)

INSERT INTO Re VALUES (NULL)
INSERT INTO Re VALUES (NULL)
INSERT INTO Re VALUES (10)
INSERT INTO Re VALUES (10)
INSERT INTO Re VALUES (20)
INSERT INTO Re VALUES (20)

SELECT * FROM Re

SELECT COUNT(A) 
FROM Re
GROUP BY (A+10)

--------------------------------------
CREATE TABLE NullCheck(
A INT,
B INT,
C INT
)

INSERT INTO NullCheck VALUES (1, NULL, 3)
INSERT INTO NullCheck VALUES (4, NULL, 6)
INSERT INTO NullCheck VALUES (7, 8, 9)

SELECT COUNT(B)
FROM NullCheck